version: '2'
services:
  manfred_dev_db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=manfred_dev_db
    volumes:
      - /var/lib/postgresql/data
